config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cabinet.views import start_page
from config import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', start_page),
    path('', include('cabinet.urls', namespace='cabinet')),
    path('', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import registration, show_login_password, user_login

app_name = UsersConfig.name

urlpatterns = [
    path('registration/', registration, name='registration'),
    path('registration/show-login-password/', show_login_password, name='show_login_password'),
    path('lk/', user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Модель пользователя"""
    username = models.IntegerField(null=True, blank=True, unique=True, verbose_name='Логин')
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=150, null=True, blank=True, verbose_name='Отчество')
    phone = models.CharField(max_length=35, unique=True, verbose_name='Телефон')
    email = models.EmailField(unique=True, verbose_name='Почта')
    create_user = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_user = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    is_active = models.BooleanField(default=True, verbose_name='Активный')

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.patronymic}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms

from users.models import User


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'patronymic', 'last_name', 'phone', 'email']


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
    # class Meta:
    #     model = User
    #     fields = ['username', 'password']

users/views.py
import random

from django.contrib.auth import authenticate, login as auth_login
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from cabinet.models import Contract, Finance
from users.forms import RegistrationForm, LoginForm
from users.models import User


def generate_unique_number() -> int:
    """Функция, которая генерирует случайное, уникальное число"""
    unique_number = ''
    for i in range(7):
        unique_number += str(random.randint(1, 9))
    if User.objects.filter(username=unique_number).exists():
        # Если число уже используется, генерируем другое
        return User.generate_unique_number()
    return int(unique_number)


def registration(request):
    """Представление регистрации пользователя"""
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            login = generate_unique_number()
            # Создание экземпляра пользователя без сохранения в базе данных
            user = User(**form.cleaned_data, username=login)
            # Устанавливаем пароль
            password = str(generate_unique_number())
            user.set_password(password)
            # Сохраняем пользователя в базе данных
            user.save()

            # Создаем договор
            title = f'{login}/{1}'
            contract = Contract.objects.create(title=title, owner=user)
            contract.save()

            # Создаем баланс к договору
            balance = Finance.objects.create(title=title, contract=contract)
            balance.save()

            # Сохраняем логин и пароль в сессии
            request.session['login'] = login
            request.session['password'] = password

            # Перенаправляем пользователя на страницу для отображения логина и пароля
            return redirect('show-login-password/')

    else:
        form = RegistrationForm()
    return render(request, 'users/registr_form.html', {'form': form})


def show_login_password(request):
    """Представление показа логина и пароля пользователю"""

    # Получаем логин и пароль из сессии
    login = request.session.get('login')
    password = request.session.get('password')

    # Проверяем и удаляем данные из сессии
    if login and password:
        del request.session['login']
        del request.session['password']

        # Записываем данные в контекст для последующей передачи в шаблон
        context = {
            'login': login,
            'password': password
        }
        return render(request, 'users/show_login_password.html', context)

    else:
        return redirect('registration')


def user_login(request):
    """Представление входа пользователя в систему"""
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # Аутентифицируем пользователя
            user = authenticate(username=int(data['username']), password=data['password'])
            # Проверяем на наличие пользователя, если есть - авторизуем
            if user and user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('cabinet:cabinet'))
            else:
                return render(request, 'users/login_form.html', {'error': 'Неверный логин или пароль'})
    else:
        form = LoginForm()
        return render(request, 'users/login_form.html', {'form': form})


class LogoutView:
    """Представление выхода пользователя из системы"""
    pass

users/templates/users/login_form.html
{% extends 'cabinet/base.html' %}

{% block content %}

<div class="sec-form center">
    <div class="form-box">
        <div class="header">
            <h1>Вход в личный кабинет</h1>
        </div>

        <form class="form-box__content" action="" method="post">
            {% csrf_token %}

            <div class="str">
                <label for="username">Логин</label>
                <input type="text" id="username" name="username" class="full-width " value="" maxlength="20"
                       required="">
            </div>

            <div class="str">
                <label for="password">Пароль</label>
                <input type="password" name="password" id="password" class="full-width " maxlength="20"
                       required="">
            </div>

            <div class="str">
                <button name="btnReg" class="btnReg">Войти</button>
            </div>
        </form>
        <div class="more-area">
            Еще не зарегистрированы? <a class="link" href="{% url 'users:registration' %}" title="Войти">Зарегистрироваться</a>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/registr_form.html
{% extends 'cabinet/base.html' %}

{% block content %}
 <div class="sec-form center">
                <div class="form-box">
                    <div class="header">
                        <h1>Регистрация</h1>
                    </div>

                    <form class="form-box__content" action="" method="post">
                        {% csrf_token %}

                        <div class="str">
                        <label for="first_name">* Имя</label>
                        <input type="text" name="first_name" id="first_name" class="full-width " maxlength="30" value="" required="">
                        </div>
                        <div class="str">
                            <label for="patronymic">Отчество</label>
                            <input type="text" name="patronymic" id="patronymic" class="full-width " maxlength="30" value="">
                        </div>
                        <div class="str">
                            <label for="last_name">* Фамилия</label>
                            <input type="text" name="last_name" id="last_name" class="full-width " maxlength="30" value="" required="">
                        </div>
                        <div class="str">
                            <label for="phone">* Номер мобильного телефона
                                <span class="tel">(будет отправлен код)</span>
                            </label>
                            <input type="tel" name="phone" id="phone" class="full-width " placeholder="+7 (999) 999-99-99" maxlength="20" minlength="5" value="+7" required="">
                        </div>
                        <div class="str">
                            <label for="email">Email</label>
                            <input type="email" name="email" id="email" class="full-width " maxlength="64" value="" required="">
                        </div>
                        <div class="str_checkbox">
                            <input type="checkbox" id="agreef" class="agree " name="agree" required="">
                            <span>Я согласен принять условия <a class="link" href="#">оферты</a></span>
                        </div>
                        <div class="str">
                            <button name="btnReg" class="btnReg">Зарегистрироваться</button>
                        </div>
                    </form>

                    <div class="more-area">
                        Уже зарегистрированы? <a class="link" href="{% url 'users:login' %}" title="Войти">Войти</a>
                    </div>
                </div>
            </div>
{% endblock %}

users/templates/users/show_login_password.html
{% extends 'cabinet/base.html' %}

{% block content %}

                <div class="sec-form center">
                    <div class="form-box">
                        <div class="box__info">
                            <table class="credentials-table">
                                <tr>
                                    <th colspan="2">Запишите свои логин и пароль, чтобы не забыть</th>
                                </tr>
                                <tr>
                                    <th>Логин</th>
                                    <td>{{ login }}</td>
                                </tr>
                                <tr>
                                    <th>Пароль</th>
                                    <td>{{ password }}</td>
                                </tr>
                            </table>
                        </div>

                        <div class="more-area">
                            <a class="link" href="{% url 'users:login' %}" title="Войти">Войти</a>
                        </div>
                    </div>
                </div>

{% endblock %}