cabinet/urls.py
from django.urls import path

from cabinet.apps import NewsConfig
from cabinet.views import NewsListView, DataBaseView, DataBaseCreateView, DataBaseUpdateView, FinanceListView

app_name = NewsConfig.name

urlpatterns = [
    path('cabinet/', NewsListView.as_view(), name='cabinet'),
    path('db/', DataBaseView.as_view(), name='db'),
    path('db/create/', DataBaseCreateView.as_view(), name='create_db'),
    path('db/update/<int:pk>/', DataBaseUpdateView.as_view(), name='update_db'),
    path('finances/', FinanceListView.as_view(), name='finances'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cabinet.views import start_page
from config import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', start_page),
    path('', include('cabinet.urls', namespace='cabinet')),
    path('', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import registration, show_login_password, user_login

app_name = UsersConfig.name

urlpatterns = [
    path('registration/', registration, name='registration'),
    path('registration/show-login-password/', show_login_password, name='show_login_password'),
    path('lk/', user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

cabinet/models.py
from django.db import models

from config import settings
from users.models import User


class News(models.Model):
    title = models.CharField(max_length=150, verbose_name='Статья')
    content = models.TextField(verbose_name='Контент')
    create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    picture = models.ImageField(null=True, blank=True, verbose_name='Изображение')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новости'
        verbose_name_plural = 'Новости'
        ordering = ['-create']


class Contract(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец', related_name='owner')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Договор'
        verbose_name_plural = 'Договоры'


class Finance(models.Model):
    title = models.CharField(max_length=10, verbose_name='Наименование')
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name='Баланс')
    contract = models.OneToOneField('Contract',
                                 on_delete=models.CASCADE,
                                 related_name='contract',
                                 verbose_name='Контракт')

    def __str__(self):
        return f'{self.title} - {self.balance}'

    class Meta:
        verbose_name = 'Баланс'
        verbose_name_plural = 'Баланс'


class DataBase(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    contract = models.ForeignKey('Contract',
                                 on_delete=models.CASCADE,
                                 related_name='contract_db',
                                 verbose_name='Договор')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'База данных'
        verbose_name_plural = 'Базы данных'

cabinet/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView

from cabinet.models import News, Contract, Finance, DataBase


def start_page(request):
    return HttpResponseRedirect(reverse('users:login'))


class NewsListView(LoginRequiredMixin, ListView):
    """Просмотр всех сущностей модели"""
    model = News

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получение авторизованного пользователя
        current_user = self.request.user

        # Получение информации о финансах и контракте
        contracts = Contract.objects.filter(owner=current_user)

        # Добавление информации о пользователе в контекст
        context['current_user'] = current_user
        context['contracts'] = contracts

        return context


class DataBaseView(LoginRequiredMixin, ListView):
    """Просмотр всех сущностей баз данных принадлежащих текущему пользователю."""
    model = DataBase

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получаем все контракты связанные с текущим пользователем
        contracts = Contract.objects.filter(owner=self.request.user)

        # Фильтруем базы данных по контрактам
        list_db = DataBase.objects.filter(contract__in=contracts)

        # Добавляем список баз данных в контекст
        context['list_db'] = list_db
        context['current_user'] = self.request.user
        context['contracts'] = contracts

        return context


class DataBaseCreateView(LoginRequiredMixin, CreateView):
    """Создание сущности DataBase"""
    model = DataBase
    fields = ('title', 'contract',)
    success_url = reverse_lazy('cabinet:db')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['current_user'] = self.request.user

        return context


class DataBaseUpdateView(LoginRequiredMixin, UpdateView):
    """Обновление сущности DataBase"""
    model = DataBase
    fields = ('title', 'contract',)
    success_url = reverse_lazy('cabinet:db')


class FinanceListView(LoginRequiredMixin, ListView):
    """Просмотр всех сущностей Finance принадлежащих текущему пользователю."""

    model = Finance

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получаем все контракты связанные с текущим пользователем
        contracts = Contract.objects.filter(owner=self.request.user)

        context['contracts'] = contracts
        context['current_user'] = self.request.user

        return context

cabinet/templates/cabinet/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход в личный кабинет | ЛК</title>
    <link rel="stylesheet" href="{% static 'css/style_registr.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_cabinet.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_db.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_fin.css' %}">
    <style>
            .form-box {
                display: flex;
                flex-direction: column;
                align-items: center;
            }

    </style>

</head>
<body>
    <div class="page-container">
        <div id="cabinet-header">
            <div class="sec-area center">
                    <div class="menu">
                        <div class="box box-left">
                                <a href="{% url 'cabinet:cabinet' %}" title="InfoCloud.Su" class="trans active">
                                <img src="{% static 'img/InfoCloud_su.png' %}" title="InfoCloud.Su" alt="InfoCloud.Su" class="menu_ua_img">
                                </a>
                        </div>
                        {% if user.is_authenticated %}
                        <div class="box box-left">
                            <a href="#" title="Мои услуги" class="trans "><span class="icon-cart icon-cabinet-header"></span>Мои услуги</a>
                        </div>
                        <div class="box box-left">
                            <a href="#" title="Журнал действий" class="trans "><span class="icon-cart icon-cabinet-header"></span>Журнал действий</a>
                        </div>
                        <div class="box box-left">
                            <a href="#" title="Профиль" class="trans "><span class="icon-cart icon-cabinet-header"></span>Профиль</a>
                        </div>
                        <div class="box box-left">
                            <a href="{% url 'users:logout' %}" title="Выход" class="trans "><span class="icon-cart icon-cabinet-header"></span>Выход</a>
                        </div>
                        {% endif %}
                    </div>

                <div class="data">
                    Техническая поддержка
                    <div class="tel">8 (8800) 201-00-00</div>
                    <a href="#" title="RMS - удаленная поддержка"><img src="{% static 'img/icon_rms_h25.png' %}" title="RMS - удаленная поддержка" height="15"> RMS - удаленная поддержка</a>
                </div>

            </div>
        </div>
        {% block content %}

        {% endblock %}
        <footer>
            <div class="sec-footer center">

            <div class="str__footer">
                <div class="data data-footer">
                ©2015-{% now 'Y' %}, ООО «ПрофИнформ». Все права защищены<br>
                Все торговые марки являются собственностью их правообладателей
                </div>
                <div class="contact">
                С уважением к Вам и Вашему делу команда ООО «ПрофИнформ»<br>
                    <span class="icon-phone"></span> 8 (8800) 201-00-00<br>
                    <span class="icon-email"></span>
                    <a class="contact__mail" href="mailto:test@infocloud.su" title="Написать электронное письмо">test@infocloud.su</a>
                </div>
                <div class="cl"></div>
            </div>

            <div class="str-info">
                <div class="info">
                Ваш браузер соединяется с сайтом по защищенному протоколу HTTPS. Сайт использует SSL-шифрование для всех передаваемых данных. Ваша личная информация под надежной защитой.
                </div>
                    <div class="cl"></div>
            </div>

            </div>
        </footer>
    </div>

</body>
</html>

cabinet/templates/cabinet/database_form.html
{% extends 'cabinet/base.html' %}

{% block content %}

<div class="sec-content center">

    {% include 'cabinet/includes/inc_left_block.html' %}

         <div class="form-box" style="align-self: flex-start; margin: 20px;">
             <div class="card" >
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                        <a href="{% url 'cabinet:db' %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>
         </div>

    <div class="container-help">
                    <div class="infodata-container">
                        <div class="str-help">
                            <div class="box">
                                Уважаемый клиент, приветствуем Вас,<br>
                                {{ current_user }}<br>
                                <span>Ваш логин:</span> {{ current_user.username }}
                            </div>
                            {% for contract in contracts %}
                            <div class="box">
                                Баланс {{ contract.title }}
                                <span style="font-weight:bold;">{{ contract.contract.balance }}</span> руб.
                            </div>
                            {% endfor %}
                        </div>
                    </div>
            </div>

</div>


{% endblock %}

cabinet/templates/cabinet/database_list.html
{% extends 'cabinet/base.html' %}

{% block content %}


<div class="sec-content center">

    {% include 'cabinet/includes/inc_left_block.html' %}

    <section class="box-db">
        <div class="header-box"><h1>Базы данных</h1></div>
        <div class="str-box__db">

            {% if list_db %}
            {% for db in list_db %}
            <a class="" href="{% url 'cabinet:update_db' db.pk %}" title="">{{ db.title }} </a>
            {% endfor %}
            {% else %}
                <div class="str-trans__db">
                    Базы данных пока еще не добавлены
                </div>
            {% endif %}
            {% if not forloop.last %}
                   <hr style="color: #eee;">
            {% endif %}

            <a class="link__db" href="{% url 'cabinet:create_db' %}" title="Создать базу данных">Создать базу данных <span
                    class="icon-right"></span></a>


            <div class="cl"></div>
        </div>
    </section>

    <div class="container-help">
                    <div class="infodata-container">
                        <div class="str-help">
                            <div class="box">
                                Уважаемый клиент, приветствуем Вас,<br>
                                {{ current_user }}<br>
                                <span>Ваш логин:</span> {{ current_user.username }}
                            </div>
                            {% for contract in contracts %}
                            <div class="box">
                                Баланс {{ contract.title }}
                                <span style="font-weight:bold;">{{ contract.contract.balance }}</span> руб.
                            </div>
                            {% endfor %}
                        </div>
                    </div>
            </div>
</div>
</div>


{% endblock %}

cabinet/templates/cabinet/finance_list.html
{% extends 'cabinet/base.html' %}

{% block content %}

<div class="sec-content center">

    {% include 'cabinet/includes/inc_left_block.html' %}

    <!--    {%for object in objects_list%}-->
    <!--    {{ object }}-->
    <!--    {% endfor %}-->

    <div class="area__finance">
        <header class="header__finance">
            <span class="icon-document icon-header"></span> Финансы
        </header>

        <div class="content">
            <div class="str__finance">
                {% for contract in contracts %}
                <div class="str-box">

                    <div class="box__finance">
                        <div class="box-l2">
                            <div style="font-size:90%"><b>{{ current_user }}</b></div>
                            <div><b>{{ contract }}</b> от {{ current_user.create_user | date:"d.m.Y" }}
                                <span style="font-size:90%;">
                                        <a class="various" data-fancybox="" data-type="iframe" data-src="" href=""> открыть</a>
                                    </span>
                            </div>
                        </div>
                        <div class="box-r2">

                            <span style="font-size:90%;">Баланс (руб)</span><br><span style="">{{ contract.contract.balance }}</span><br>
                        </div>
                    </div>


                    <div class="box__finance">
                        <div class="box-l2">
                            <a class="box-l2__link " href="/services-2949">Услуги  </a>
                            <a class="box-l2__link " href="/invoices-2949">Счета  </a>
                            <a class="box-l2__link " href="/accacts-2949">Акты  </a>
                            <a class="box-l2__link " href="/payments-2949">Платежи  </a>
                            <a class="box-l2__link " href="/charges-2949">Начисления  </a>
                            <a class="box-l2__link " href="/revises-2949">Акты сверки </a>
                        </div>
                        <div class="box-r2">
                            <a class="box-l2__link " href="/finances-pay-2949">Пополнить</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="cl"></div>
        </div>
    </div>

    <div class="container-help">
        <div class="infodata-container">
            <div class="str-help">
                <div class="box">
                    Уважаемый клиент, приветствуем Вас,<br>
                    {{ current_user }}<br>
                    <span>Ваш логин:</span> {{ current_user.username }}
                </div>
                {% for contract in contracts %}
                <div class="box">
                    Баланс {{ contract.title }}
                    <span style="font-weight:bold;">{{ contract.contract.balance }}</span> руб.
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

cabinet/templates/cabinet/news_list.html
{% extends 'cabinet/base.html' %}

{% block content %}

        <div class="sec-content center">

            {% include 'cabinet/includes/inc_left_block.html' %}

            <section class="box-news">
                <div class="header-box"><h1>Новости</h1></div>
                {% for object in object_list %}
                <div class="str-box">
                    <div class="date" style="font-size: 12px; color: #ccc;">{{ object.create }}</div>
                        <div class="head">
                            <a class="head__link" style="color: red;" href="#" target="_blank">{{ object.title }}</a>
                        </div>
                            <div class="news_block_content">
                                {% if object.picture %}
                                <a class="news_block_img" href="#" target="_blank" style="float:left;">
                                    <img src="/media/{{ object.picture }}" style="max-width:160px;">
                                </a>
                                {% endif %}
                                <div class="news_block_lead" style="padding-left:173px">
                                    <p>
                                        {{object.content}}
                                    </p>
                                </div>
                            </div>
                        <div class="cl"></div>
                </div>
                {% if not forloop.last %}
                   <hr style="color: #eee;">
                   {% endif %}
                {% endfor %}
            </section>

            <div class="container-help">
                    <div class="infodata-container">
                        <div class="str-help">
                            <div class="box">
                                Уважаемый клиент, приветствуем Вас,<br>
                                {{ current_user }}<br>
                                <span>Ваш логин:</span> {{ current_user.username }}
                            </div>
                            {% for contract in contracts %}
                            <div class="box">
                                Баланс {{ contract.title }}
                                <span style="font-weight:bold;">{{ contract.contract.balance }}</span> руб.
                            </div>
                            {% endfor %}
                        </div>
                    </div>
            </div>
    </div>
                </div>
{% endblock %}